### ISSUE TITLE
Upload code you already have

### ISSUE THREAD

**Issue by kipkurui** [BioinfoNet/Data-mining#5]
@Shuyib  and @kamondemwangi, there was some code you guys had created that is not yet added to the repo. Kindly include it so that we can build upon it. You can use branches to add incomplete code

**Comment by kamondemwangi** [comment]
OK,  on it will add the one we had modified

**Comment by kamondemwangi** [comment]
i have uploaded the edited code we used to extract the first 2000 pubmed ids and abtracts

**Comment by Shuyib** [comment]
Hi @kipkurui will post as soon as i get time to myself in South Africa. It's been really hectic...

**Comment by kipkurui** [comment]
Great @Shuyib. Let us know when you have uploaded the code. As you can see [here](https://github.com/BioinfoNet/Data-mining/blob/master/check-access.md), I have checked for open access information. Now we need to do a time series binned analysis to check how open access trends have changed over the years.

**Comment by Shuyib** [comment]
Thanks @kipkurui going through the document. I made a branch of what we did last time let me know if you want me to work on the whole dataset as well.

**Comment by Shuyib** [comment]
Good the file is alright beginning data manipulation to make the plot.

**Comment by kipkurui** [comment]
Great @shuyib. Have a look and let me know if you can work on it, I'll also find some time next week to analyze.

**Comment by Shuyib** [comment]
We have a merge conflict could you help me with it. Not sure how to mend it then I can continue making the plot. Expect it by the end to tomorrow latest.

**Comment by kipkurui** [comment]
Done.
